name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python lectures/build.py
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
